export const GET_APPOINTMENT_PENDING = "GET_APPOINTMENT_PENDING";
export const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS";
export const GET_APPOINTMENT_ERROR = "GET_APPOINTMENT_ERROR";

export const ADD_APPOINTMENT_PENDING = "ADD_APPOINTMENT_PENDING";
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_ERROR = "ADD_APPOINTMENT_ERROR";

export const EDIT_APPOINTMENT_PENDING = "EDIT_APPOINTMENT_PENDING";
export const EDIT_APPOINTMENT_SUCCESS = "EDIT_APPOINTMENT_SUCCESS";
export const EDIT_APPOINTMENT_ERROR = "EDIT_APPOINTMENT_ERROR";

export const DELETE_APPOINTMENT_PENDING = "DELETE_APPOINTMENT_PENDING";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_ERROR = "DELETE_APPOINTMENT_ERROR";
