export const GET_PET_PENDING = "GET_PET_PENDING";
export const GET_PET_SUCCESS = "GET_PET_SUCCESS";
export const GET_PET_ERROR = "GET_PET_ERROR";

export const ADD_PET_PENDING = "ADD_PET_PENDING";
export const ADD_PET_SUCCESS = "ADD_PET_SUCCESS";
export const ADD_PET_ERROR = "ADD_PET_ERROR";

export const EDIT_PET_PENDING = "EDIT_PET_PENDING";
export const EDIT_PET_SUCCESS = "EDIT_PET_SUCCESS";
export const EDIT_PET_ERROR = "EDIT_PET_ERROR";

export const DELETE_PET_PENDING = "DELETE_PET_PENDING";
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS";
export const DELETE_PET_ERROR = "DELETE_PET_ERROR";
