export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const PUT_USER_PENDING = "PUT_USER_PENDING";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_ERROR = "PUT_USER_ERROR";
